### ISSUE TITLE
Build failed with exception

### ISSUE THREAD

**Issue by prantikv** [creacore-team/cordova-plugin-smslog#1]
Getting the following when I try to build app using `ionic cordova build android`

```
BUILD FAILED


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

here is my ionic info.
```

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.9.2

System:
    Android SDK Tools : 25.2.5
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 10
```

**Comment by Bruno361** [comment]
This does not necessarily seems related to the cordova-plugin-smslog.
Please check your build environment and/or provide more detailed information about the actual error you have.

**Comment by prantikv** [comment]
I removed the plugin and it works fine. So yes this is related to the plugin.

**Comment by Bruno361** [comment]
The plugin has been updated and some errors corrected. Can you try again and confirm that everything works ok for you ?

**Comment by prantikv** [comment]
The build works now but I have some other questions regarding the working of the plugin.

Firstly, the link in returned values no longer works here https://github.com/creacore-team/cordova-plugin-smslog#returned-values

Is there a way to get the value of the SMS. Also, can we attach a listener that will be called when a new message arrives?

**Comment by Bruno361** [comment]
@prantikv 
Thanks, I updated the README.

The goal of this plugin is to recover the "Logs", reading the SMS content is therefore out of the scope of this plugin. There is now a bodyLength value, tough, that gives you the length of the SMS.

For this and a listener to get notified of new messages, you might want to have a look at other plugins:
https://www.npmjs.com/package/cordova-plugin-smsreceivers
https://www.npmjs.com/package/cordova-plugin-gm-sms
